theme: jekyll-theme-cayman
title: <a href="https://abradaric.me"><img id="avatar" src="https://i.imgur.com/EVLE5mf.jpeg" height="256px" alt="Hi"/></a>
description: <span id="greeting">howdy, stranger ðŸ‘‹</span>
#google_analytics: UA-127612098-1
